name: Deploy Content to Azure Sentinel
on: 
  push:
    branches: [ bugbash-1 ]
    paths:
    - 'Detections/**'
    - '.github/workflows/sentinel-deploy**'

jobs:
  deploy-content:
    runs-on: windows-latest
    env:
      resourceGroupName: 'cac-test-rg'
      workspaceName: 'cac-bugbash-workspace'
      directory: '${{ github.workspace }}/Detections'
      cloudEnv: 'AzureCloud'
      creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_1c44b273cb30493d9a6952b8f562bd52 }}

    steps:
    - name: Login to Azure
      uses: azure/login@v1
      if: ${{ env.cloudEnv == 'AzureCloud' }}
      with:
        creds: ${{ secrets.AZURE_SENTINEL_CREDENTIALS_1c44b273cb30493d9a6952b8f562bd52 }}
        enable-AzPSSession: true

    - name: Checkout
      uses: actions/checkout@v1

    - name: Read deployment script
      id: deploymentScript
      uses: juliangruber/read-file-action@v1
      with:
        path: '${{ github.workspace }}/.github/workflows\azure-sentinel-deploy.ps1'
    
    - name: Deploy Analytic Rules
      uses: azure/powershell@v1
      with:
        azPSVersion: 'latest'
        inlineScript: |
          ${{ steps.deploymentScript.outputs.content }}